### ISSUE TITLE
TextCellEditor maxlen config

### ISSUE THREAD

**Issue by simonzack** [webismymind/editablegrid#10]
Hi,

Is it possible to make maxlen configurable?
It defaults to 255, this is a bit short for my purposes, I have to change the source to make it bigger
function TextCellEditor(size, maxlen, config) { this.fieldSize = size || -1; this.maxLength = maxlen || 255; if (config) this.init(config); };

thanks

**Comment by gnzlst** [comment]
Hi, any news on this? Is it possible to set the max-length when editing a specific column?
