### ISSUE TITLE
Lock Columns from Being Editable

### ISSUE THREAD

**Issue by jeremyw24** [webismymind/editablegrid#111]
Nice work on the framework - I want to lockout some columns so they are no longer editable when displayed in the browser, I have tried a few things but nothing seems to fix this.. I am using the SQL Version - everything else works a treat!

**Comment by nickmacwiz** [comment]
In your editablegrid.php file on the add column line you need to add ', NULL, false' after the type of data. See the example line below. 


$grid->addColumn('lastname', 'Last Name', 'string', NULL, false);

**Comment by jeremyw24** [comment]
Sweet thanks!
