### ISSUE TITLE
Multiple editablegrid table in the same page

### ISSUE THREAD

**Issue by capaaway** [webismymind/editablegrid#114]
Hi , coul someone help me to insert more than one editablegrid table in the same html page?
The pourpose is to have 3 editable of the same table , filtered in 3 different ways .
Thanks!
Fabio

**Comment by webMac** [comment]
Hi, 
this is how it works for me:

1. Just define one <div id="grid1/2/3/.."></div> Tag per editable grid you want to use
2. Init and handle each editable grid with it's own JavaScript code reffering your html div id


_somehow like that:_

	<!DOCTYPE html>
	<html>
		<head>
			<title>Two Grids</title>
			<script src="editablegrid.js"></script>
			<script type="text/javascript">
				var editableGrid1 = new window.EditableGrid("grid1", {
					editmode: "static"
					// ...
				});
				// editableGrid1.tableLoaded = function(){ ... };
				// editableGrid1.modelChanged= function(){ ... };

				var editableGrid2 = new window.EditableGrid("grid2", {
					editmode: "static"
					// ...
				});
				// editableGrid2.tableLoaded = function(){ ... };
				// editableGrid2.modelChanged= function(){ ... };

			</script>
		</head>
		<body>
			<h1>Grid 1</h1>
			<div id="grid1"></div>
			<h1>Grid 2</h1>
			<div id="grid2></div>
		</body>
	</html>

**Comment by capaaway** [comment]
Thanks!
Fabio
