### ISSUE TITLE
Can it fetch 1000 records in Select Dropdown?

### ISSUE THREAD

**Issue by coolguys5253** [webismymind/editablegrid#126]
We want to fetch 1000 Customer Names in Select Dropdown Like this But Whole Page is blank???

$grid->addColumn('Customer_No', 'Customer', 'string', fetch_pairs($mysqli,'SELECT No, Name FROM customers'),true ); in loaddata.php

**Comment by jybeaujean** [comment]
Try to call loaddata.php directly in your browser and send me the result.

**Comment by coolguys5253** [comment]
Hello Jean,

It is showing Blank Page. Thanks a lot for your concern.

I have attached My folder containing all file with demo.sql of my database
also

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by nikolassharp** [comment]
@coolguys5253 I'm not sure but probably your issue may be related to PHP's maximum limit in 1000 max_input_vars in a request. Accidently I've had the same problem few months ago and debuging with php_errors shows php's error when sending more than 1000 var in request.

Look for this also:
http://stackoverflow.com/questions/8710185/new-limit-within-php-1000-fields-per-post-does-someone-know-if-the-number-can

**Comment by coolguys5253** [comment]
It was char encoding as Jean suggested.

Thanks for your advice too :)

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
