### ISSUE TITLE
Unable to locate examples/demo.html file

### ISSUE THREAD

**Issue by sarojthapa60** [webismymind/editablegrid#130]
I could see examples/full/demo.js and examples/full/demo.css, but I could not locate examples/demo.html. Is it just the examples/index.html file?
Thanks

**Comment by vasadhananjay** [comment]
It's actually the examples/full/index.php by the look of it.

**Comment by vasadhananjay** [comment]
<script src="https://gist.github.com/vasadhananjay/c0b24e4f10b4150c64069102374d8afe.js"></script>

**Comment by vasadhananjay** [comment]
Need this too:

[https://gist.github.com/vasadhananjay/c0b24e4f10b4150c64069102374d8afe.js](url)

**Comment by sarojthapa60** [comment]
Thank you so much
