### ISSUE TITLE
Loading Data from CSV

### ISSUE THREAD

**Issue by dewanshamsul** [webismymind/editablegrid#137]
I was checking the csv example from editablegrid-master/examples/full/datasource/demo.php
But for some reason it returns the output attached. I'm not sure what's wrong. Can you have a look at it and let me know what's missing here?
![csvoutput](https://cloud.githubusercontent.com/assets/22762429/19260919/736c60d4-8faf-11e6-92d5-df3acd444372.png)

**Comment by makoru-hikage** [comment]
The best solution you can get is transform that into JSON whenever possible. The the product will be absorbed by the Table.

**Comment by dewanshamsul** [comment]
I've imported CSV to MySQL table.
