### ISSUE TITLE
Make a row readonly

### ISSUE THREAD

**Issue by saintelaitlait** [webismymind/editablegrid#144]
Hey guys, is it possible to make a row readonly instead of a column?

Thank you!

**Comment by jybeaujean** [comment]
Sure ! You have to create a dedicated Editor that checks if the cell is editable or not. 

`setCellEditor("firstname",new MyOwnEditor({});`

https://github.com/webismymind/editablegrid/blob/master/editablegrid_editors.js

**Comment by saintelaitlait** [comment]
Thank you my friend!

**Comment by louisantoinem** [comment]
If you just want to make the row read-only, implementing the callback "isEditable" is the easiest solution. It allows to decide dynamically if a column, row or cell should be editable or read-only.

Example:

<pre>
myEditableGrid.isEditable = function(rowIndex, columnIndex) {
    // make first row readonly
    return rowIndex > 0;
};
</pre>
