### ISSUE TITLE
How can I set focus on a cell?

### ISSUE THREAD

**Issue by ramonYcajal** [webismymind/editablegrid#145]
I really don´t understand how the focus works in this grid, but when I remove a row, I lost the focus and i want to know how can I set the focus un a cell after remove a row, positioning it into the closest cell or an expecific cell.
All the doc of this grid does not explain at all.

**Comment by ramonYcajal** [comment]
Solved, with the editCell() method, now, when I remove a row, focus goes to the next row and positioning into the first editable cell.

**Comment by simivar** [comment]
@ramonYcajal if it's solved please close the issue.
