### ISSUE TITLE
Adding a button inside the cells of the ACTION column 

### ISSUE THREAD

**Issue by bigandy131** [webismymind/editablegrid#150]
If I want a button inside the action column. How would I do that. Right now it do not show up automatically with the gird load in my code. I have to click on the cell  twice for my button to show up..

first drop down box pop up. Then i click on one of the options(everything say undefined at first).Then my button pop up. 
A script in my index.html

  <script>
      var count=0;
      var i=0;
      var x=1;
      window.onload = function() {
                  editableGrid = new EditableGrid("DemoGridJSON",{enableSort:true,pageSize:25}); 
                  
                  editableGrid.tableRendered= function() {  updatePaginator(editableGrid);
              
                  
                  editableGrid.setCellI haveer("ACTION", new CellRenderer({ 
                                     render: function(cell, id) {                 
                                                     //cell.innerHTML+= "<i onclick=\"editablegrid.deleteRow("+id+");\" class='fa fa-trash-o red' ></i>";
                                                    
                                                     i=document.getElementsByClassName("number editablegrid-DEPTID");
                                                    
                                                    
                                                     cell.innerHTML+= "<button style='background-color:red;color:white; border-radius:12px;text-align:center;' onclick=\"editableGrid.deleteRow("+i[x].innerText+");\">Delete </button>";
                                                       x++;
                      }
          })); 
};

    
  

        editableGrid.tableLoaded = function() { editableGrid.renderGrid("tablecontent", "testgrid"); };
       
        editableGrid.loadJSONFromString(editableGrid.loadJSON("loaddata.php"));

        //editableGrid.tableLoaded = function() { editableGrid.renderGrid("tablecontent", "testgrid"); };

        editableGrid.modelChanged= function(rowIndex, columnIndex, oldValue, newValue, row){
          updateCellValue(editableGrid, rowIndex, columnIndex, oldValue, newValue, row)
        };

       
      
  

         $("#filter").keyup(function() {
                    editableGrid.filter( $(this).val());

                    // To filter on some columns, you can set an array of column index 
                    //datagrid.editableGrid.filter( $(this).val(), [0,3,5]);
                  });

                $("#showaddformbutton").click( function()  {
                  showAddForm();
                });
                $("#cancelbutton").click( function() {
                  showAddForm();
                });

                $("#addbutton").click(function() {
                  editableGrid.addRow();
               });

      }
     
    </script>

-----------------------------------------------------------------------how i load my data(loaddata.php)---------------

$retArr = array();

$retArr["metadata"] = array( array("name" => "DEPTID","label" => "DEPTID","datatype"=>"integer","values"=>"NULL","editable"=>"false"),
					  array("name"=>"DEPT_CODE", "label"=>"DEPT_CODE","datatype"=>"string","editable"=>"true"),
					  array("name"=>"DEPT_DESC", "label"=>"DEPT_DESC","datatype"=>"string","editable"=>"true"),
					  array("name"=>"DEPT_PRIMARY_CHG_ACCT", "label"=>"DEPT_PRIMARY_CHG_ACCT","datatype"=>"string","editable"=>"true"),
					  array("name"=>"EDIT_DATE", "label"=>"EDIT_DATE","datatype"=>"date","editable"=>"false"),
					  array("name"=>"EDIT_CLERK", "label"=>"EDIT_CLERK","datatype"=>"string","editable"=>"false"),
					  array("name"=>"ACTION", "label"=>"ACTION","datatype"=>"html","values"=>"NULL","editable"=>"false","field"=>"id"));

$current=array();
$total=array();

$sql = oci_parse($conn,"select * from fac.mp_dept");
oci_execute($sql,OCI_DEFAULT);

while ($arr = oci_fetch_assoc($sql)) {

             	$retArr["data"][] = (array("id"=>$arr["DEPTID"],"values"=>array("DEPTID"=>$arr["DEPTID"],"DEPT_CODE"=>$arr["DEPT_CODE"],"DEPT_DESC"=>$arr["DEPT_DESC"],"DEPT_PRIMARY_CHG_ACCT"=> $arr["DEPT_PRIMARY_CHG_ACCT"],"EDIT_DATE"=>$arr["EDIT_DATE"],  "EDIT_CLERK"=>$arr["EDIT_CLERK"] )));
             

                

                 }

echo   json_encode($retArr);

**Comment by TxEdgeMan** [comment]
It is really hard to read when your pasted code isn't formatted.  Need a call to setCellRender for 'action'.

Change:
editableGrid.tableLoaded = function() { 
        editableGrid.renderGrid("tablecontent", "testgrid"); 
};

TO:
editableGrid.tableLoaded = function() { 
        this.setCellRender("action", new CellRenderer({
               render:  function(cell,id, rowIndex) {
                      cell.innerHtml+= "<i onclick=\"yourJavaScriptActionFunctionGoesHere;\" class='fa fa-info green'></i>";
                }
        }));
        editableGrid.renderGrid("tablecontent", "testgrid"); 
};


NOTE:  Class is using the font awesome CSS to display an 'info' button.  Change / omit as you see fit.

**Comment by bigandy131** [comment]
This is no longer an issue for me. sorry about that. I fix this problem i had a while back.
