### ISSUE TITLE
Is there any local storage example?

### ISSUE THREAD

**Issue by willess** [webismymind/editablegrid#169]
I'am desperate looking for an example with local storage. Can someone help me?

**Comment by MSIH** [comment]
What purpose do you want to use local storage? Did you save some data in local storage and now you want to render in the grid?

**Comment by willess** [comment]
I do have a html grid. And when I edit a cell I want to save the filled in data. So, when you refresh the page, you still see the data that's filled in.

**Comment by curtisnewton** [comment]
yes, the same here ... loading data from a .json file, but how to save changes or added lines???
i know, javascript are not allowed to save to the webserver (sure, security), but PHP can do it. But how to get the array data from javascript to a php dara array??? there are no examples here ... why not?
Thanks

**Comment by donlaur** [comment]
Php is server side.  JavaScript is client side.  Meaning that php runs first on the server and is sent to the client and run on the client.

You want to get the array data from JavaScript to PHP?  Can't do it naturally but could maybe use something like Ajax or an API call to save out.
