### ISSUE TITLE
How to get XML data not using php?

### ISSUE THREAD

**Issue by sbeleidy** [webismymind/editablegrid#18]
I'm currently using this with bottlepy and python and I am linking it to a sqlite3 database. 
I've written code that can generate XML code based on the data I need from the database and I can display this very easily. 
I also have code written for generating data from XML code. 

The issue now is how do I get new XML code if the user changes the data. I know there is a function in php but for some reason I can't get that to work. And I don't know how I would be able to interface that with the rest of my python code to send it back to the database.

Please let me know if there is already a way. I am willing to contribute to this project if there is no current way to do this. Let me know what path I can follow to get this to work.

Thanks

**Comment by ceprio** [comment]
Look at https://github.com/ceprio/editablegrid-python-sqlite-example . You will find the python code that handles table changes and bring them back to the database.
