### ISSUE TITLE
Append returns "html" column to default

### ISSUE THREAD

**Issue by Nonononoki** [webismymind/editablegrid#200]
I have an "html" type column in my table, which looks like this:
`<button class="btn" onClick="openModal(this)" val="[]"><i class="fa fa-edit"></i></button>`
 
After modifying the "val" attribute to my preferred value, appending a row will reset all buttons to their default state.

EDIT: Removing a row has the same effect.

**Comment by crivadavi** [comment]
What do you mean by append a row? In which context? Can you post a sample code of what you are trying to do?

**Comment by Nonononoki** [comment]
@crivadavi

Example code: 

```
var editable = new EditableGrid("editable_id");
editable.append(2, {"selected": false, "name": "", "btn":`<button class="btn" onClick="openModal(this)" id=${maxId_creator}><i class="fa fa-edit"></i></button>`});
```

**Comment by crivadavi** [comment]
Did you do something on events "tableRendered" or "tableFiltered" that could cause a redraw of the table, resetting all the buttons?

**Comment by Nonononoki** [comment]
I actually do I think. I use these functions:

```
editable.load({"metadata": metadata "data": data});
editable_edit.renderGrid(...);
```

But why are only the buttons resetted but boolean, integer and string cells unaffected? And what would be the alternative? Because I want the table to show newly added rows.

**Comment by crivadavi** [comment]
With the method 
 ```javascript
editable.load({"metadata": metadata "data": data});
```

you are redrawing the table with the object "data" you put in. Are you sure that the variable data contains the updated values of the row you have modified?
Check that value, or another solution could be to call method "refreshGrid". So, after you have appended a new row write:

 ```javascript
 editable.refreshGrid()
```
