### ISSUE TITLE
Add a new row

### ISSUE THREAD

**Issue by jcketz** [webismymind/editablegrid#37]
Hi! First of all thanks a lot for this wonderful library.

I have succeeded importing it to a django server and make it work with python. auto saving each value modification to server.

But now I'd like to append an empty row except the first column which is the index row value. Do you have a scripted example for that? 

I've tried the duplicate() and the insertAfter() value. but it doesn't changes the current row values but the previous one. and also import the this.getrowvalues(this.getRowcount-1). Do you have an easy way to do that? Thanks a lot

**Comment by webMac** [comment]
How about 

editableGrid.append(editableGrid.data.length, { 'yourDefaultKey1': 'yourDefaultValue1' }, true);

?
