### ISSUE TITLE
Big tables.

### ISSUE THREAD

**Issue by kafran** [webismymind/editablegrid#46]
It would be nice to have checkboxes to select witch columns are shown on large tables. =)

**Comment by Nicolax** [comment]
Hello
Any new about this "future" new feature?
Thanx a lot
Regards,

**Comment by jybeaujean** [comment]
Hi,

This feature is available but not documented. Now, columns have a visibility state.
Check : https://github.com/webismymind/editablegrid/commit/c7776578f9ba84fadbce11e5f9cb5b16125ef396
