### ISSUE TITLE
Change not saved back to the xml file

### ISSUE THREAD

**Issue by sylbon** [webismymind/editablegrid#71]
Dear Editablegrid team,

Thank you for this great project !
I m checking your demo examples and I m surprised that the changed (my input in cells) are not saved back to the xml file (they come from).
What shall i do so that the update works  ?

Thank you,

Best regards,

Sylvain

**Comment by marvinschwartz** [comment]
I would like to do the same thing by adding a procedure to the function modelChanged  in simple.js.
However I can not see how to access the xml file so that I an change the record modified.

Do you have some example code for reading and writing to the xml file?
I will then add a function to add/delete records form the xml file.

cheers
George

**Comment by tbenbrahim** [comment]
This a JavaScript UI library, do you know of any JavaScript libraries that can write to the user's disk?
The XML files are for simulating loading data from a server, you will have to write your own code for loading and saving data to the server, using AJAX.

**Comment by marvinschwartz** [comment]
i gave up trying to use xml and moved to an sql database

**Comment by curtisnewton** [comment]
It is a pity that there are never productive comments and solutions to a simple question.
It seems that no concrete solutions are offered here just to make money or for the self-satisfaction of their ego?
We all know that javascript has no write access to the filesystem, that was not the initial question. 
The question was how the loaded xml data from the example can be saved back to the xml file.
This can be achieved through ajax request and/or php solution, but there is a lack of information that works like javascript data could be transfered, preferably by $_POST. Presumably a solution with a maximum of 10 lines of program code. 
So who has the nuts and can deliver this solution?

**Comment by tbenbrahim** [comment]
@curtisnewton  The solution will depend on your back end (Java, PHP, .Net, Ruby, Python, NodejS, etc...), and it is trivial to implement, but **well outside the scope** of a *client side* JavaScript library.
If you really do not know how to do this, you should ask on StackOverflow for a solution that matches your back end platform.

**Comment by curtisnewton** [comment]
who can read is clearly in the advantage ...
NOW i can understand @marvinschwartz and his attitude

perhaps good product, bad documentation and very bad service. bye
