### ISSUE TITLE
Display number of records in header/footer

### ISSUE THREAD

**Issue by rmingas** [webismymind/editablegrid#74]
Hi,

I might be on the wrong place to ask this question, but would like to know:

Is is possible to display on header and/or footer the number of current records found (including filtered content)?

**Comment by thenderson** [comment]
EditableGrid.prototype.getTotalRowCount is defined in editablegrid.js.

**Comment by rmingas** [comment]
I'm Using the MySQL version

**Comment by rmingas** [comment]
Hello, guys. Any ideas? I'd really appriceate suggestions on this feature for MySQL version

**Comment by jybeaujean** [comment]
use : 
EditableGrid.prototype.getRowCount() : Returns the number of rows
or : 
EditableGrid.prototype.getUnfilteredRowCount() : Returns the number of rows, not taking the filter into account if any
