### ISSUE TITLE
$customRowAttributes - Changing background-color?

### ISSUE THREAD

**Issue by TheUFFP** [webismymind/editablegrid#77]
I'm not at all sure what the $customRowAttributes variable does or where custom variables are being created and passed, but is there a simple way to change a row's background-color based on the data contained in the row?  For example, highlight all of the rows that don't have a value in a "Completed Date" column.

**Comment by thenderson** [comment]
I just figured this out recently, so hopefully this helps you. I added a custom renderer to the cells in the date column of my grid that formats the date the way I want it, then adds a specific class to each cell or row (depending), based on the value of the cell. CSS does the rest.

```javascript
			this.setCellRenderer('due_by', new CellRenderer({ //shades row based on how soon commitment is due
				render: function(cell, value) {
					date_due=moment(value, 'YYYY-MM-DD')
					cell.innerHTML=date_due.format("\'YY.MM.DD");
					row=self.grid.getRow(cell.rowIndex);
					status=self.grid.getValueAt(cell.rowIndex, 6);
					how_soon=date_due.diff(moment(),'days');
					if (status == 'closed') {
						$(row).addClass('closed');
					}
					else {
						due_class = how_soon < -7 ? 'overdue_2w' : (how_soon < 0 ? 'overdue_1w' : (how_soon < 8 ? 'due_nextweek' : 'due_future'));
						$(cell).addClass(due_class);
					}
				}}));

**Comment by thenderson** [comment]
... and here's the CSS that relates to the above:

```CSS
.overdue_2w {/* for table rows > 2 weeks overdue */
	background-color: rgba(221, 128, 71, .45);
}

.overdue_1w {/* for table rows < 2 weeks overdue */
	background-color: rgba(216, 178, 92, .4);
}

.due_nextweek {/* for table rows due next week */
	background-color: rgb(228, 228, 228);
}

**Comment by webMac** [comment]
I used the same technic with setting a CSS class when putting together my xml string for the editablegrid table. 

In a switch / case statement i add the class info to the xml string when putting it together with a string builder in c#:
  switch(...)
    case ABC: 
        XmlData.Append(String.Format("<row id='{0}' class='rowGreen'>", RowId++));
  . . .

**Comment by webMac** [comment]
Also, please note that these custom CSS settings implement changing row background colors for you: 
```css
    tr:nth-child(even){
        background: rgb(250, 250, 250);
    }

    tr:nth-child(odd) {
        background: rgb(240, 240, 240);
    }
```
