### ISSUE TITLE
Usage as a Matrix

### ISSUE THREAD

**Issue by smcpoland** [webismymind/editablegrid#78]
hi,

I would like to use the editablegrid as a full matrix, for example, where each cell is individually OnHover, OnSelect etc. For example a 10x10 matrix with 100 selectable cells, what happens after that is obviously down to other code but this is my requirement.

How would one do this?

Thanks in advance,

**Comment by webMac** [comment]
I did it by using XML as a data container and parse it manually. So i parsed the XML string line by line and picked out the data by the column names into collections and the like which i handle for updating/saving later in the program. Same procedure when showing it in a grid was manually put the XML string together with variable column length by using a loop over the given data set.
