### ISSUE TITLE
work with multiple tables

### ISSUE THREAD

**Issue by TasPats** [webismymind/editablegrid#82]
I seek for JavaScript library for CRUD application for a while and found EditableGrid as perfect solution

but it works perfectly with one MySQL table (implemented from your MySQL example)
when I need to work with multiple tables, I run in some problems - demo.js is tailored for very concrete table (ok, I rework this for universal solution) - so add.php and load.php

how to deal with this is best? make separate .php files for every table or make some abstraction to operate all tables with one add.php, load.php file

also (but it may be my limited knowledge) I can't work with tables, if it main index not named as 'id'

**Comment by jybeaujean** [comment]
Hi,

I think that you should work with an MVC model. So the javascript calls every appropriate controllers that manage all CRUD operations.

**Comment by TasPats** [comment]
yes, I think that it is right way, but I don't think that my qualifications is not so high, that my solution is suitable for others and therefore I don't want go far from original 'editablegrid' team source

**Comment by alphokinyua** [comment]
Am having the same problem working with different MySQL tables. I have created different loaddata.php files for each table, the data loads fine but it does not update new values. it shows that update was successful by displaying the cool green color but, on refresh it shows the old values. Please help me work with multiple MySQL tables. Urgently need help am stuck and I find EditableGrid to be a powerful and user friendly library for CRUD operations.
Please help
};
