### ISSUE TITLE
attachToHTMLTable edit

### ISSUE THREAD

**Issue by appleabryant** [webismymind/editablegrid#84]
This bug is closed, but it is still happening (perhaps a regression?)
To see it in action, simply run the "Attaching grid to an HTML table" demo:
http://www.editablegrid.net/editablegrid/examples/attach/index.html
Sort any column and click inside the cells... editable data does not match the sorted cell data.

-Andrew

**Comment by webismymind** [comment]
Please use the last version available from GitHub (as stated here: http://editablegrid.net/en/download)

Louis

**Comment by appleabryant** [comment]
I am.

**Comment by webismymind** [comment]
I just tested the demo you pointed out on the latest sources and the bug
has been resolved.

Please find enclosed the latest minified version we made.

Regards,
Louis

2015-02-14 2:50 GMT+01:00 appleabryant <notifications@github.com>:

**Comment by webismymind** [comment]
Here:
https://www.dropbox.com/s/2pnn3aakfdpjn6p/editablegrid-2.1.0-b27.tar.gz?dl=0

2015-02-14 3:36 GMT+01:00 Louis Antoine <louisantoinem@gmail.com>:

**Comment by appleabryant** [comment]
Thank you.
