### ISSUE TITLE
Scrollbar

### ISSUE THREAD

**Issue by XinYiMan** [webismymind/editablegrid#85]
Hello , I have created a grid , I would like , however, that he had a fixed size with the scroll bar horizontally and vertically.

**Comment by webMac** [comment]
just us a .css stylesheet file and set fixed values for your table or even the single columns. I.E.: 

table.yourgrid { 
	width: 800px;
}

However, nowerdays you more likely define a min-width and a max-width property, and in between you set the width property to a relative value in %. 
So your table could look like:


table.yourgrid { 
	width: calc(100% - 60px);  /* makes your table 100% of your screen but leaves a boarder on each side i.e. with use of the  margin: 30px;  property */
	min-width:  400px;
	max-width: 1600px;
}

and width the linking columns the like ...

.col-0 { width: 20% }
.col-1 { width: 20% } 
...

**Comment by jybeaujean** [comment]
You should deal with 'overflow' in your CSS
