### ISSUE TITLE
Line Chart

### ISSUE THREAD

**Issue by ibuilder** [webismymind/editablegrid#87]
Any examples using an line chart instead of a bar or pie chart?

This is awesome btw.

**Comment by webMac** [comment]
kindly have a look at the Open Flash Chart site:
http://teethgrinder.co.uk/open-flash-chart-2/
maybe you can use it as described there or contribute new stuff to the repository here..

**Comment by webismymind** [comment]
Note that in the latest sources (master branch), we've added support for Highcharts, which is way better than OFC in my opinion. Highcharts requires no Flash and has at least as much features as OFC, and it is a very active project. Adding support for line charts would be easy.
