### ISSUE TITLE
editablegrid with postgresql

### ISSUE THREAD

**Issue by bionhan** [webismymind/editablegrid#94]
Thanks a lot for this great work.

I would like to use editablegrid with PostGreSQL so I've begun to change the "loaddata.php" file : 

```php
//connection
$db_connexion = pg_connect("host=192.168.9.130 port=5432 dbname=nhan_db user=nhan password=1234");

//query
$result = pg_query($db_connexion,'SELECT * FROM demo');
```

But it doesn't work... Is it because "$result" has to be a mysqli result ?

Best regards,

Nhan

**Comment by jybeaujean** [comment]
You have to transform $result in an array before pass it to renderJSON. 
Perhaps try : pg-fetch-all ? http://php.net/manual/fr/function.pg-fetch-all.php
Like this : 

$grid->renderJSON(pg_fetch_all($result)) ;

**Comment by bionhan** [comment]
Thanks a lot for your quick answer ! It worked :)

**Comment by khomsun** [comment]
editablegrid with mssql 2000 
help me  please.

**Comment by jybeaujean** [comment]
I don't know mssql.  Perhaps you should read the doc : http://php.net/manual/fr/book.mssql.php
